### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by okason97** [okason97/signLanguageRecognition#1]
Dejo los modelos y tecnicas que encontre y me parecieron copados ordenados segun cuan performante hayan sido en diferentes competencias de clasificacion.
EnsembleNet https://arxiv.org/abs/1901.05798 Es la tecnica que esta dando mejores resultados. Se divide la red en branches y al final se concatenan las branches para dar la clasificacion. (necesita mas estudio)
ResNet Muy buenos resultados en general. Facil de entrenar
Dual Path network https://arxiv.org/abs/1707.01629
senet Squeeze and exitation model https://arxiv.org/abs/1709.01507
Prototypical networks https://arxiv.org/abs/1703.05175 buenos para pocos datos aparentemente
SE-ResNet = fusion senet + resnet
densenet121 https://arxiv.org/abs/1608.06993 
Xception
Inception
Siamese network
pnasnet
nasnet

Referencias
1) http://image-net.org/challenges/LSVRC/2017/results
2) https://www.kaggle.com/sudalairajkumar/winning-solutions-of-kaggle-competitions
3) https://machinelearningmastery.com/ensemble-methods-for-deep-learning-neural-networks/
4) https://www.kaggle.com/c/humpback-whale-identification/discussion/82366
5) https://medium.com/@ducha.aiki/thanks-radek-7th-place-solution-to-hwi-2019-competition-738624e4c885
6) https://www.kaggle.com/c/human-protein-atlas-image-classification/discussion/78109
7) https://drive.google.com/file/d/1Rnhl_BAI816gDM7fw4ZdGrVlyg20NXLi/view
8) http://www.it4nextgen.com/keras-image-classification-models/

Resumen
Segun lo investigado. El modelo mas utilizado es utilizan ensemble net con Resnet, senet, densenet y/o nasnet. En ese orden fue la cantidad de modelos ganadores encontrados que los utilicen. Tambien se mencionan la utilizacion de siamese networks y dual path networks. Y se menciona como futuro estudio la implementacion de prototypical networks para datasets con pocos datos. En kaggle (2) se pueden encontrar multiples guias a diferentes soluciones ganadoras de concursos junto a codigo de algunas e informacion sobre preprocesamiento, etc.
https://www.kaggle.com/c/inclusive-images-challenge
https://www.kaggle.com/c/human-protein-atlas-image-classification
https://www.kaggle.com/c/humpback-whale-identification
Son algunos concursos de los que se puede aprender bastante.

**Comment by facundoq** [comment]
# Datasets
* LSA16
* RWTH

# Modelos

* [Prototypical Networks for Few-shot Learning](https://arxiv.org/abs/1703.05175)
* [DenseNet](https://arxiv.org/abs/1608.06993)
* [SENet](https://arxiv.org/pdf/1709.01507.pdf)
* [ShakeShake](https://arxiv.org/abs/1705.07485)
* [Pyramidal Residual Networks](https://medium.com/@sh.tsang/review-pyramidnet-deep-pyramidal-residual-networks-image-classification-85a87b60ae78)
