### ISSUE TITLE
Prototypical Network

### ISSUE THREAD

**Issue by ulises-jeremias** [okason97/signLanguageRecognition#3]
@okason97 En el repositorio [prototypical-networks-tf](https://github.com/ulises-jeremias/prototypical-networks-tf) ya está subido el código con un README.md en el que se explica la distribución de directorios. Está exitosamente probada con Omniglot verificando las métricas que se muestran en el paper. Me falta definir un detalle mínimo para poder probarla con `lsa16` así podemos comparar con DenseNet.

Para que quede a modo de historial, el detalle exacto que me falta es modificar el archivo[protonet/data/lsa16.py](https://github.com/ulises-jeremias/prototypical-networks-tf/blob/develop/protonet/data/lsa16.py) para poder convertir la data original al formato `[n_classes, n_img, w, h, c]`. Si se termina eso se pueden seguir los pasos del readme para correr la red sin problemas!

Hoy lo termino de ver!

**Comment by facundoq** [comment]
y= vector de clases
x = vector de imágenes [n,h,w,c]
i=np.argsort(y)
x=x[i,:,:,:] # ordeno por clase
np.reshape(x,(n_classes,n_per_class,h,w,c))

Asumiendo que n_per_class es el mismo para todas las clases no? Sino no se
puede codificar como un array.
