### ISSUE TITLE
Mejorar modelo

### ISSUE THREAD

**Issue by ulises-jeremias** [okason97/signLanguageRecognition#4]
Voy a estar investigando si tiene sentido buscar mejorar prototypical utilizando tecnicas como SENet y ShakeShake.

**Comment by facundoq** [comment]
imho apples to oranges, vamos a tener algo que explicar si hay una
diferencia sustancial entre modelos, aumentarle 1% con shakeshake no creo
que contribuya mucho, pero bueno quizás vale probar
